/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uern.di.les.ifcpn;

import br.uern.di.les.ifcpn.graphics.Background;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Rodrigo
 */
public class MainIFCPN extends javax.swing.JFrame {
    
    public static JLabel[] estacoes;
    protected boolean serverIsAlive = false;
    Servidor s;
    /**
     * Creates new form MainIFCPN
     */
    public MainIFCPN() {
        setContentPane(new Background());
        initComponents();
        estacoes = new JLabel[]{estacao1,estacao2, estacao3, estacao4, estacao5, estacao6, estacao7};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estacao6 = new javax.swing.JLabel();
        estacao1 = new javax.swing.JLabel();
        estacao5 = new javax.swing.JLabel();
        estacao2 = new javax.swing.JLabel();
        estacao4 = new javax.swing.JLabel();
        estacao7 = new javax.swing.JLabel();
        estacao3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface For Colored Petri Networks - IFCPN");
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(780, 390));
        setResizable(false);

        estacao6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uern/di/les/ifcpn/res/estacaoLivre.png"))); // NOI18N

        estacao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uern/di/les/ifcpn/res/estacaoLivre.png"))); // NOI18N

        estacao5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uern/di/les/ifcpn/res/estacaoLivre.png"))); // NOI18N

        estacao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uern/di/les/ifcpn/res/estacaoLivre.png"))); // NOI18N

        estacao4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uern/di/les/ifcpn/res/estacaoLivre.png"))); // NOI18N

        estacao7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uern/di/les/ifcpn/res/estacaoLivre.png"))); // NOI18N

        estacao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uern/di/les/ifcpn/res/estacaoLivre.png"))); // NOI18N

        jMenuBar1.setPreferredSize(new java.awt.Dimension(90, 23));

        jMenu1.setText("Arquivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Iniciar Servidor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        jMenuItem2.setText("Sobre o Programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(estacao6)
                .addGap(182, 182, 182)
                .addComponent(estacao5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(estacao4)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(estacao1)
                        .addGap(224, 224, 224)
                        .addComponent(estacao2))
                    .addComponent(estacao7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(667, Short.MAX_VALUE)
                    .addComponent(estacao3)
                    .addGap(21, 21, 21)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estacao1)
                    .addComponent(estacao2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estacao5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(estacao6, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(estacao7)
                .addGap(42, 42, 42)
                .addComponent(estacao4)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(estacao3)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new SobreOPrograma().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IFCPN();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {    
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new MainIFCPN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel estacao1;
    private static javax.swing.JLabel estacao2;
    private static javax.swing.JLabel estacao3;
    private static javax.swing.JLabel estacao4;
    private static javax.swing.JLabel estacao5;
    private static javax.swing.JLabel estacao6;
    private static javax.swing.JLabel estacao7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
    
    private void IFCPN(){        
            if(!serverIsAlive){
                System.out.println("Iniciando servidor...");
                s = new Servidor();
                s.start();
                serverIsAlive = true;
            } else {
                System.out.println("O servidor já está em funcionamento!");
            }
    }
    
}
